version: "3.9"

services:
  bot:
    container_name: aggregate_bot
    build:
      context: ../
    env_file:
      - ../.env
    environment:
      MONGODB_URI: 'mongodb://mongo_db/'
    networks:
      - bot_network
    depends_on:
      mongo_db:
        condition: service_started
    entrypoint: bash -c "cd /app/src/data && python3 loaddata.py && cd /app && python3 run.py"

  mongo_db:
    container_name: mongo_db
    image: mongo
    restart: always
    volumes:
      - /mongodb/data:/var/lib/mongodb/data
    ports:
      - "27017:27017"
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

volumes:
  mongodb: